### ISSUE TITLE
Cookie已经获取，但是脚本提示错误。

### ISSUE THREAD

**Issue by sysnxw** [chouchoui/QuanX#1]
你好，在圈x已经配置完成，cookie 也提示获取成功，已经禁用cookie 获取脚本。但是运行脚本，提示如下。
iOS 13.5 v1.0.12-build335

{"error":["\u4f60\u4eca\u5929\u5df2\u7ecf\u7b7e\u5230\u4e86(\u4ee5\u5f53\u524d\u670d\u52a1\u5668\u65f6\u95f4 2020-07-20 08:56:03 \u8ba1\u7b97)"],"time":1595206563}

**Comment by chouchoui** [comment]
QuanX没有弹出下面通知内容吗？
```json
{
    "error": [
        "你今天已经签到了(以当前服务器时间 2020-07-20 08:56:03 计算)"
    ],
    "time": 1595206563
}
```

**Comment by sysnxw** [comment]
看了下通知栏，有提示已经签到了。
不好意思，关闭了QX的通知提示，没注意到。打扰。
