### ISSUE TITLE
大佬  Dq  的小程序更新了   签到用不了了

### ISSUE THREAD

**Issue by Asphyxia2464** [chouchoui/QuanX#10]

**Comment by chouchoui** [comment]
才提交过代码，更新引用以后进商城tab重新获取下cookie。
我还不确定明天能不能正常用，之前cookie没有时效性的，这次更新过后如果有时效的话可能要放弃脚本了。

**Comment by Asphyxia2464** [comment]
> 才提交过代码，更新引用以后进商城tab重新获取下cookie。
> 
> 我还不确定明天能不能正常用，之前cookie没有时效性的，这次更新过后如果有时效的话可能要放弃脚本了。

好的大佬我去试试

**Comment by Asphyxia2464** [comment]
> 才提交过代码，更新引用以后进商城tab重新获取下cookie。
> 
> 我还不确定明天能不能正常用，之前cookie没有时效性的，这次更新过后如果有时效的话可能要放弃脚本了。

大佬  我更新后提示过去cookie 失败

**Comment by chouchoui** [comment]
> > 才提交过代码，更新引用以后进商城tab重新获取下cookie。
> > 我还不确定明天能不能正常用，之前cookie没有时效性的，这次更新过后如果有时效的话可能要放弃脚本了。
> 
> 大佬 我更新后提示过去cookie 失败

再次更新引用脚本，尝试修复了。

**Comment by Asphyxia2464** [comment]
> > > 才提交过代码，更新引用以后进商城tab重新获取下cookie。
> 
> > > 我还不确定明天能不能正常用，之前cookie没有时效性的，这次更新过后如果有时效的话可能要放弃脚本了。
> 
> > 
> 
> > 大佬 我更新后提示过去cookie 失败
> 
> 
> 
> 再次更新引用脚本，尝试修复了。

大佬可以了 
 谢谢大佬了  坐等cookie 有效期

**Comment by Asphyxia2464** [comment]
> > > > 才提交过代码，更新引用以后进商城tab重新获取下cookie。
> > 
> > > > 我还不确定明天能不能正常用，之前cookie没有时效性的，这次更新过后如果有时效的话可能要放弃脚本了。
> > 
> > > 
> > 
> > > 大佬 我更新后提示过去cookie 失败
> > 
> > 
> > 
> > 再次更新引用脚本，尝试修复了。
> 
> 大佬可以了 
>  谢谢大佬了  坐等cookie 有效期

**Comment by Asphyxia2464** [comment]
> 了。

看来是没办法了  cookie会过期了 上午刚获取  下午就失效了

**Comment by chouchoui** [comment]
> 看来是没办法了 cookie会过期了 上午刚获取 下午就失效了
感谢测试反馈，看来这个脚本只能放弃了。
