### ISSUE TITLE
修改iOS天气脚本似乎不能工作

### ISSUE THREAD

**Issue by tanglueyi** [chouchoui/QuanX#3]
App: Surge TF
是我配置不对吗？
![IMG_3693](https://user-images.githubusercontent.com/3315564/108931959-87702880-7683-11eb-9b3b-37190da19421.jpg)
![IMG_3692](https://user-images.githubusercontent.com/3315564/108931967-8939ec00-7683-11eb-9fcf-e65273dd2a71.PNG)
![IMG_3691](https://user-images.githubusercontent.com/3315564/108931969-89d28280-7683-11eb-9baf-9b721eb88c92.jpg)
![IMG_3690](https://user-images.githubusercontent.com/3315564/108931971-89d28280-7683-11eb-8533-e611f2ec7150.PNG)
![IMG_3689](https://user-images.githubusercontent.com/3315564/108931972-8a6b1900-7683-11eb-8f59-4b7eb759f7eb.PNG)

**Comment by chouchoui** [comment]
可以直接用这个模块 [https://raw.githubusercontent.com/chouchoui/QuanX/master/iOS_Weather_AQI_Standard.sgmodule](https://raw.githubusercontent.com/chouchoui/QuanX/master/iOS_Weather_AQI_Standard.sgmodule)

**Comment by tanglueyi** [comment]
> 可以直接用这个模块 https://raw.githubusercontent.com/chouchoui/QuanX/master/iOS_Weather_AQI_Standard.sgmodule

感谢回复，我自己也有模块的。我的初衷就是不想装模块了，没有其他办法了吗

**Comment by chouchoui** [comment]
文件内的脚本写法是原作者直接写的，我在测试的时候好像也不能成功
和模块里写法唯一区别好像是`requires-body=true`改为`requires-body=1`

**Comment by tanglueyi** [comment]
> 文件内的脚本写法是原作者直接写的，我在测试的时候好像也不能成功
> 和模块里写法唯一区别好像是`requires-body=true`改为`requires-body=1`

这样没有解决问题，看来还是老老实实用模块吧。

**Comment by chouchoui** [comment]
```
AQI-US = type=http-response, requires-body=1, pattern=^https:\/\/weather-data\.apple\.com\/v1\/weather\/[\w-]+\/([0-9]+\.[0-9]+)\/([0-9]+\.[0-9]+)\?, script-path=https://raw.githubusercontent.com/chouchoui/QuanX/master/Scripts/iOS_Weather_AQI_Standard/index.js
```
将这段替换您的配置，主楼里的配置用的还是原作者脚本路径

**Comment by tanglueyi** [comment]
> ```
> AQI-US = type=http-response, requires-body=1, pattern=^https:\/\/weather-data\.apple\.com\/v1\/weather\/[\w-]+\/([0-9]+\.[0-9]+)\/([0-9]+\.[0-9]+)\?, script-path=https://raw.githubusercontent.com/chouchoui/QuanX/master/Scripts/iOS_Weather_AQI_Standard/index.js
> ```
> 
> 将这段替换您的配置，主楼里的配置用的还是原作者脚本路径

原来是我搞错了脚本路径，谢谢指正，现在能够起效了
