### ISSUE TITLE
nag刮墙无法获取cookie

### ISSUE THREAD

**Issue by litesheng** [chouchoui/QuanX#6]
已经杀后台重新进入了还是无法获取cookie

**Comment by chouchoui** [comment]
点到任务里试下

**Comment by litesheng** [comment]
> 点到任务里试下

试过了，假如你测试有效的话那可能是我这边软件版本的问题

**Comment by litesheng** [comment]
> 点到任务里试下

脚本记录里正常运行了，但是无法获取cookie

**Comment by chouchoui** [comment]
![image](https://user-images.githubusercontent.com/14866249/134795743-a8528c66-5e02-4770-b8a4-56c7cf934752.png)
左侧Surge，右侧Quantumult X

劳烦进行一次获取cookie操作（杀后台重新开软件，进入任务页），是否看到相关日志信息

**Comment by litesheng** [comment]
> ![image](https://user-images.githubusercontent.com/14866249/134795743-a8528c66-5e02-4770-b8a4-56c7cf934752.png)
> 左侧Surge，右侧Quantumult X
> 
> 劳烦进行一次获取cookie操作（杀后台重新开软件，进入任务页），是否看到相关日志信息

emmm，我用的是loon，不过我quanx也试了，确实不行，我等下再试下

**Comment by litesheng** [comment]
> ![image](https://user-images.githubusercontent.com/14866249/134795743-a8528c66-5e02-4770-b8a4-56c7cf934752.png)
> 左侧Surge，右侧Quantumult X
> 
> 劳烦进行一次获取cookie操作（杀后台重新开软件，进入任务页），是否看到相关日志信息

用的第三方客户端，不知道怎么发图片。看了日志，只有“开始”和“结束”，没有“成功”

**Comment by litesheng** [comment]
> ![image](https://user-images.githubusercontent.com/14866249/134795743-a8528c66-5e02-4770-b8a4-56c7cf934752.png)
> 左侧Surge，右侧Quantumult X
> 
> 劳烦进行一次获取cookie操作（杀后台重新开软件，进入任务页），是否看到相关日志信息

算了不麻烦了，可能是软件版本低了

**Comment by chouchoui** [comment]
> 算了不麻烦了，可能是软件版本低了

好，那我关闭issue了
